In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from mlxtend.plotting import plot_decision_regions

In [7]:
dataset=pd.read_csv('./placement.csv')

In [8]:
dataset.head()

cgpa  package
0  6.89     3.26
1  5.12     1.98
2  7.82     3.25
3  7.42     3.67
4  6.94     3.57

In [35]:
x=dataset.iloc[:,:-1]
y=  dataset['package']

In [36]:
new_data=dataset.head(10)

In [37]:
from sklearn.model_selection import LeaveOneOut,LeavePOut,KFold,StratifiedKFold

In [38]:
x_new=new_data.iloc[:,:-1]
y_new=new_data['package']

In [39]:
lo=LeaveOneOut()

In [40]:
for train,test in lo.split(x_new,y_new):
    print('train',train)
    print('test',test)
    print('-------------------')

train [1 2 3 4 5 6 7 8 9]
test [0]
-------------------
train [0 2 3 4 5 6 7 8 9]
test [1]
-------------------
train [0 1 3 4 5 6 7 8 9]
test [2]
-------------------
train [0 1 2 4 5 6 7 8 9]
test [3]
-------------------
train [0 1 2 3 5 6 7 8 9]
test [4]
-------------------
train [0 1 2 3 4 6 7 8 9]
test [5]
-------------------
train [0 1 2 3 4 5 7 8 9]
test [6]
-------------------
train [0 1 2 3 4 5 6 8 9]
test [7]
-------------------
train [0 1 2 3 4 5 6 7 9]
test [8]
-------------------
train [0 1 2 3 4 5 6 7 8]
test [9]
-------------------


In [41]:
lp=LeavePOut(p=2)

for train,test in lp.split(x_new,y_new):
    print('train',train)
    print('test',test)
    print('-------------------')

train [2 3 4 5 6 7 8 9]
test [0 1]
-------------------
train [1 3 4 5 6 7 8 9]
test [0 2]
-------------------
train [1 2 4 5 6 7 8 9]
test [0 3]
-------------------
train [1 2 3 5 6 7 8 9]
test [0 4]
-------------------
train [1 2 3 4 6 7 8 9]
test [0 5]
-------------------
train [1 2 3 4 5 7 8 9]
test [0 6]
-------------------
train [1 2 3 4 5 6 8 9]
test [0 7]
-------------------
train [1 2 3 4 5 6 7 9]
test [0 8]
-------------------
train [1 2 3 4 5 6 7 8]
test [0 9]
-------------------
train [0 3 4 5 6 7 8 9]
test [1 2]
-------------------
train [0 2 4 5 6 7 8 9]
test [1 3]
-------------------
train [0 2 3 5 6 7 8 9]
test [1 4]
-------------------
train [0 2 3 4 6 7 8 9]
test [1 5]
-------------------
train [0 2 3 4 5 7 8 9]
test [1 6]
-------------------
train [0 2 3 4 5 6 8 9]
test [1 7]
-------------------
train [0 2 3 4 5 6 7 9]
test [1 8]
-------------------
train [0 2 3 4 5 6 7 8]
test [1 9]
-------------------
train [0 1 4 5 6 7 8 9]
test [2 3]
-------------------
train [0 1

In [42]:
kf=KFold(n_splits=5)

for train,test  in kf.split(x_new,y_new):
    print('train',train)
    print('test',test)
    print('-------------------')

train [2 3 4 5 6 7 8 9]
test [0 1]
-------------------
train [0 1 4 5 6 7 8 9]
test [2 3]
-------------------
train [0 1 2 3 6 7 8 9]
test [4 5]
-------------------
train [0 1 2 3 4 5 8 9]
test [6 7]
-------------------
train [0 1 2 3 4 5 6 7]
test [8 9]
-------------------


In [43]:
# st=StratifiedKFold(n_splits=5)

# for train,test  in st.split(x_new,y_new):
#     print('train',train)
#     print('test',test)
#     print('-------------------')


In [44]:
from sklearn.model_selection import cross_val_score

In [45]:
from sklearn.linear_model import LogisticRegression

In [46]:
from sklearn.svm import SVR

In [55]:
from sklearn.tree import DecisionTreeRegressor

In [47]:
from sklearn.ensemble import RandomForestRegressor

In [48]:
from sklearn.linear_model import LinearRegression

In [65]:
cross_val_score(LinearRegression(),x,y,cv=KFold(n_splits=12))

array([0.65607733, 0.81109125, 0.79272659, 0.78170388, 0.85105282,
       0.71730765, 0.75873584, 0.55321381, 0.8162863 , 0.70647335,
       0.64263203, 0.71828236])

In [66]:
cross_val_score(SVR(),x,y,cv=KFold(n_splits=12))

array([0.61955958, 0.77522624, 0.74178636, 0.80272996, 0.80938592,
       0.72351076, 0.78669229, 0.51558159, 0.81638632, 0.73587917,
       0.60833431, 0.71746417])

In [71]:
p=cross_val_score(RandomForestRegressor(),x,y,cv=KFold(n_splits=12))
p.sort()
p

array([0.43928473, 0.4591763 , 0.54179739, 0.55067287, 0.64102714,
       0.65907397, 0.6804184 , 0.68816837, 0.68900925, 0.69232851,
       0.70947807, 0.73263246])

In [73]:
cross_val_score(DecisionTreeRegressor(),x,y,cv=KFold(n_splits=12))

array([0.34297124, 0.56269226, 0.61691488, 0.62167462, 0.63975593,
       0.55994921, 0.62855899, 0.39519471, 0.59708798, 0.35298295,
       0.4084877 , 0.55125025])

In [74]:
from sklearn.neighbors import KNeighborsRegressor

In [78]:
cross_val_score(KNeighborsRegressor(),x,y,cv=KFold(n_splits=20))

array([ 0.17607668,  0.67013097,  0.66377351,  0.80100579,  0.69577399,
        0.71546173,  0.80869397,  0.70533279,  0.7887696 ,  0.26907197,
        0.72800937,  0.60551679,  0.67098135,  0.30601277,  0.85125982,
        0.74205266,  0.62674456, -0.03181098,  0.64113406,  0.73930071])