In [1]:
import numpy as np;

In [3]:
#creating a matrix using numpy

matrix_1=np.array([[1,2,3],[4,5,6],[7,8,9]])
                  

In [4]:
print(matrix_1.shape)

(3, 3)


In [5]:
print(matrix_1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
#creating matrix with random values

In [9]:
random_matrix=np.random.rand(6, 7)

In [10]:
print(random_matrix)

[[0.67228989 0.44705805 0.78718842 0.78622635 0.27656716 0.23287078
  0.68047789]
 [0.76896296 0.73979496 0.09118303 0.46592164 0.05485415 0.81765694
  0.63238307]
 [0.53169686 0.15518261 0.472689   0.84201909 0.16983447 0.44368178
  0.06024966]
 [0.83308969 0.54174881 0.71461379 0.50554035 0.53424665 0.12956846
  0.56407951]
 [0.77725392 0.2884373  0.13425445 0.61194927 0.84573897 0.3472899
  0.18875993]
 [0.70292479 0.07571016 0.90235735 0.65453374 0.79127613 0.14701549
  0.78648641]]


In [11]:
#creating matrix with random integers


In [12]:
random_integer_matrix=np.random.randint(100,size=(4,5))

In [13]:
print(random_integer_matrix)

[[26 81 37 93 96]
 [41 73 95 81 94]
 [29 76 78 46  5]
 [90 39 82 36 74]]


In [20]:
matrix_ones=np.ones((4,5),dtype=int)



In [21]:
print(matrix_ones)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [22]:
null_matrix=np.zeros((4,5),dtype=int)

In [23]:
print(null_matrix)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [24]:
#identity matrix
identity_matrix=np.eye(5,6,dtype=int)

In [25]:
print(identity_matrix)

[[1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]]


In [26]:
#transpose matrix
a= np.random.randint(100,size=(4,5))
print(a)

[[24 10 21 12  1]
 [21 55 62 52 17]
 [54 75  8 72 32]
 [ 6 58 24 62 79]]


In [27]:
transpose_of_a=np.transpose(a)

In [28]:
print(a)

[[24 10 21 12  1]
 [21 55 62 52 17]
 [54 75  8 72 32]
 [ 6 58 24 62 79]]


In [29]:
print(transpose_of_a)

[[24 21 54  6]
 [10 55 75 58]
 [21 62  8 24]
 [12 52 72 62]
 [ 1 17 32 79]]


In [30]:
transpose_of_a.shape

(5, 4)

In [31]:
a.shape

(4, 5)