In [1]:
import numpy as np;


In [2]:
A=np.array([[1,2,3],[4,5,6],[7,8,9]])
B=np.array([[1,2,3],[4,5,6],[7,8,9]])

c=A+B

In [3]:
print(c)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [5]:
#creating two matrices with random valus
matrix_1=np.random.randint(10,size=(3,3))
matrix_2=np.random.randint(10,size=(3,3))


In [6]:
sum=np.add(matrix_1,matrix_2)

In [7]:
print(sum)

[[ 7  6  6]
 [14  4 12]
 [ 8 17  7]]


In [9]:
#creating two matrices with random values
matrix_1=np.random.randint(10,size=(3,3))
matrix_2=np.random.randint(10,size=(3,3))
suntract=np.subtract(matrix_1,matrix_2)

In [11]:
print(suntract)

[[ 6  5  1]
 [-6  2  5]
 [ 1  6 -2]]


In [12]:
x=5
y=np.random.randint(10,size=(4,4))

In [13]:
product=np.multiply(x,y)

In [14]:
print(product)

[[20 20 10 15]
 [ 5 15 20 20]
 [10 40 30  0]
 [ 5  0 15 35]]


In [21]:
##creating two matrices with random values
matrix_1=np.random.randint(10,size=(3,3))
matrix_2=np.random.randint(10,size=(3,4))


In [22]:
print(matrix_1)


[[9 4 3]
 [2 0 8]
 [3 7 3]]


In [23]:
print(matrix_2)

[[1 5 0 2]
 [8 4 4 5]
 [7 2 4 0]]


In [24]:
#multiply

In [25]:
mutiply=np.dot(matrix_1,matrix_2)

In [26]:
print(mutiply)

[[62 67 28 38]
 [58 26 32  4]
 [80 49 40 41]]


In [28]:
matrix1=np.random.randint(10,size=(3,3))
matrix2=np.random.randint(10,size=(3,3))

In [31]:
print(matrix1)
print(matrix2)

[[0 1 1]
 [4 3 2]
 [1 0 9]]
[[1 1 9]
 [4 7 5]
 [9 9 1]]


In [32]:
product=np.multiply(matrix1,matrix2)


In [33]:
print(product)

[[ 0  1  9]
 [16 21 10]
 [ 9  0  9]]
