In [2]:
# //Numpy -numerical python


In [2]:
# Advantages of numpy arrays
# 1.allow several mathematical operations
# 2.faster operations
import numpy as np;

In [2]:
print('hello world')

hello world


In [3]:
# List vs numpy --->Time taken
from time import process_time


In [6]:
# Time taken by list

python_list=[i for i in range(1000000)];
start_time=process_time();
python_list=[i+5 for i in python_list];
end_time=process_time();

print("Time taken by list is ",end_time-start_time);

Time taken by list is  0.109375


In [12]:
#time taken by numpy array

np_array=np.array([i for i in range(1000000)]);
start_time=process_time();
np_array=np_array+5;
end_time=process_time();
# Convert start_time and end_time to 8-digit floating point precision strings
start_time_str = f"{start_time:.8f}"
end_time_str = f"{end_time:.8f}"

# Print the start and end times with 8-digit floating point precision
print(f"Start time: {start_time_str}")
print(f"End time: {end_time_str}")
time_taken = float(end_time_str) - float(start_time_str)
print(f"Time taken by numpy array: {time_taken:.8f} seconds")
print(f"Time taken by numpy array: {end_time - start_time:.12f} seconds");

Start time: 2.70312500
End time: 2.70312500
Time taken by numpy array: 0.00000000 seconds
Time taken by numpy array: 0.000000000000 seconds


In [14]:
#Numpy arrays
#list 
list1=[1,2,3,4,5]
type(list1)

list

In [17]:
np_array=np.array([1,2,3,4,5])
print(type(np_array))

<class 'numpy.ndarray'>


In [18]:
a=np.array([1,2,3,4])

In [19]:
a.shape

(4,)

In [20]:
b= np.array([[1,2,3],[4,5,6]])
b.shape

(2, 3)

In [21]:
c= np.array([[1,2,3,6,9],[8,9,10,11,12]],dtype='float')

In [22]:
print(c)

[[ 1.  2.  3.  6.  9.]
 [ 8.  9. 10. 11. 12.]]


In [23]:
#placeholder in array

In [25]:
#inital placeholder in numpy arrays
#create a numpy array with zero values

x=np.zeros((4,5),dtype='int') # row,colum
print(x)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [36]:
# create a arrow of ones
y=np.ones((4,5),dtype='int') # row,colum
z=np.arange(20).reshape(4,5);

In [40]:
print(y)
print(z)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [41]:
print(np.multiply(x,y))
print(np.multiply(z,y))

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [42]:
#array of particular value


In [44]:
c=np.full((4,5),5)
print(c)

[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]]


In [48]:
#create an identity matrix same rows and columns
a=np.eye(4,dtype='int')

In [49]:
print(a)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [50]:
#create an numpy array with random values
b=np.random.random((3,4))

In [56]:
#create a numpy array with random values 
b=np.random.random((3,4))
print(b)

[[0.94971514 0.48058521 0.07615166 0.72973129]
 [0.44456772 0.25512736 0.76864636 0.19526556]
 [0.21129371 0.62818422 0.13412243 0.40303129]]


In [57]:
c=np.random.randint(10,100,(5,6))

In [58]:
print(c)

[[31 48 54 17 73 13]
 [14 42 55 86 71 99]
 [39 90 26 98 75 66]
 [95 14 35 42 39 95]
 [72 95 93 65 41 71]]


In [59]:
# array of evenly spaced values
d=np.linspace(10,30,5)

In [60]:
print(d)

[10. 15. 20. 25. 30.]


In [3]:
#array of evenly spaced values ---> specifying the values
e=np.arange(10,30,5);
print(e)

[10 15 20 25]


In [4]:
#convert a list  to array 
list2=[1,2,3,4,5]
np_array=np.asarray(list2)

In [5]:
print(np_array)

[1 2 3 4 5]


In [6]:
type(np_array)

numpy.ndarray

In [9]:
#analysis of numpy array
c=np.random.randint(10,90,(5,6))

In [10]:
print(c)


[[55 47 44 70 23 49]
 [63 38 58 15 28 16]
 [88 46 75 89 51 35]
 [23 16 23 35 69 18]
 [33 56 21 52 38 16]]


In [11]:
#array dimension
c.shape

(5, 6)

In [12]:
print(c.ndim)
#number of dimensions

2


In [14]:
print(c.size)
#number of elements

30


In [16]:
#checking data type of values in the array
print(c.dtype)

int32


In [17]:
#mathematical operation on a np array

In [20]:
list1=[1,2,3,4,5];
list2=[8,9,10,11,12,];
print(list1+list2);

[1, 2, 3, 4, 5, 8, 9, 10, 11, 12]


In [21]:
np_array1=list1+list2;

In [22]:
print(np_array1)

[1, 2, 3, 4, 5, 8, 9, 10, 11, 12]


In [23]:
np_array=np.array([list1,list2])

In [24]:
print(np_array)

[[ 1  2  3  4  5]
 [ 8  9 10 11 12]]


In [25]:
a=np.random.randint(0,10,(3,3))

In [26]:
print(a)

[[3 4 7]
 [2 4 5]
 [3 4 8]]


In [27]:
b=np.random.randint(10,20,(3,3))

In [29]:
print(b)

[[15 15 19]
 [11 13 11]
 [11 11 13]]


In [30]:
print(a+b)

[[18 19 26]
 [13 17 16]
 [14 15 21]]


In [31]:
print(a-b)

[[-12 -11 -12]
 [ -9  -9  -6]
 [ -8  -7  -5]]


In [32]:
print(a*b)

[[ 45  60 133]
 [ 22  52  55]
 [ 33  44 104]]


In [33]:
print(a/b)

[[0.2        0.26666667 0.36842105]
 [0.18181818 0.30769231 0.45454545]
 [0.27272727 0.36363636 0.61538462]]


In [34]:
a=np.random.randint(0,10,(3,3))
b=np.random.randint(10,20,(3,3))
print(a)
print(b)

[[8 5 5]
 [7 4 7]
 [4 3 0]]
[[15 12 17]
 [18 19 11]
 [14 14 16]]


In [35]:
print(np.add(a,b))

[[23 17 22]
 [25 23 18]
 [18 17 16]]


In [36]:
print(np.subtract(a,b))

[[ -7  -7 -12]
 [-11 -15  -4]
 [-10 -11 -16]]


In [37]:
print(np.multiply(a,b))

[[120  60  85]
 [126  76  77]
 [ 56  42   0]]


In [38]:
print(np.divide(a,b))

[[0.53333333 0.41666667 0.29411765]
 [0.38888889 0.21052632 0.63636364]
 [0.28571429 0.21428571 0.        ]]


In [39]:
#array manipulation

In [40]:
array=np.random.randint(0,10,(4,5));
print(array)
print(array.shape)

[[1 7 7 3 3]
 [8 6 3 5 6]
 [4 2 7 9 8]
 [2 4 9 3 6]]
(4, 5)


In [42]:
#transpose 
trans=np.transpose(array);
print(trans)
trans.shape 

[[1 8 4 2]
 [7 6 2 4]
 [7 3 7 9]
 [3 5 9 3]
 [3 6 8 6]]


(5, 4)

In [43]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])

[2 3 4 5]


In [44]:

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[:4])

[1 2 3 4]


In [45]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-3:-1])

[5 6]


In [46]:

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[::2])

[1 3 5 7]


In [51]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr)
print(arr[0, 1:4])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[2 3 4]


In [52]:

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr)
print(arr[0:2, 1:4])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[2 3 4]
 [7 8 9]]


In [53]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [54]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [55]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  print(x)

[1 2 3]
[4 5 6]


In [56]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  for y in x:
    print(y)

1
2
3
4
5
6


In [57]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [58]:

arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)
arr1= np.concatenate((arr1, arr2), axis=0)
print(arr1)

print(arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


In [59]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)

print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [60]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [61]:

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))

print(arr)

[[1 2 3]
 [4 5 6]]


In [62]:

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.dstack((arr1, arr2))

print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


In [63]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [64]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 4)

print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [65]:
import numpy as np

# Create an array
arr = np.array([1, 2, 3, 4, 5, 6])

# Split the array into two arrays
arr1, arr2 = np.split(arr, 2)

# Print the resulting arrays
print(arr1)
print(arr2)

[1 2 3]
[4 5 6]


In [66]:
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [67]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


In [68]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 1)

print(x)

(array([0, 2, 4, 6], dtype=int64),)


In [69]:
arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7)

print(x)

1


In [70]:
arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7, side='right')

print(x)

2


In [71]:

arr = np.array([1, 3, 5, 7])

x = np.searchsorted(arr, [2, 4, 6])

print(x)

[1 2 3]


In [72]:
arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr))

['apple' 'banana' 'cherry']


In [4]:
#reshaping an array
import numpy as np
a=np.random.randint(2,10,(3,4))
print(a)

[[2 2 6 8]
 [8 9 6 9]
 [2 2 5 3]]


In [5]:
print(a.shape)

(3, 4)


In [6]:
a=a.reshape(4,3)

In [7]:
print(a)

[[2 2 6]
 [8 8 9]
 [6 9 2]
 [2 5 3]]
