In [1]:
#pandas are useful for Data processing and analysis
#pandas DataFrame is a 2-dimensional labeled data structure with columns of potentially different types
#import the pandas library 
import pandas as pd;

In [2]:
#creating pandas dataFrame 

In [15]:
#importing boston data house price data
# Download the dataset from UCI repository
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/housing/housing.data"
column_names = [
    "CRIM", "ZN", "INDUS", "CHAS", "NOX", "RM", "AGE", "DIS", "RAD", "TAX",
    "PTRATIO", "B", "LSTAT", "MEDV"
]

# Load the dataset into a pandas DataFrame
boston_housing = pd.read_csv(url, delim_whitespace=True, names=column_names)

In [16]:
type(boston_housing)

pandas.core.frame.DataFrame

In [17]:
from sklearn.datasets import fetch_california_housing

# Load the California housing dataset
california_housing = fetch_california_housing()

In [18]:
type(california_housing)

sklearn.utils._bunch.Bunch

In [19]:
print(boston_housing)

        CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0    0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296.0   
1    0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242.0   
2    0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242.0   
3    0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222.0   
4    0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222.0   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...    ...   
501  0.06263   0.0  11.93     0  0.573  6.593  69.1  2.4786    1  273.0   
502  0.04527   0.0  11.93     0  0.573  6.120  76.7  2.2875    1  273.0   
503  0.06076   0.0  11.93     0  0.573  6.976  91.0  2.1675    1  273.0   
504  0.10959   0.0  11.93     0  0.573  6.794  89.3  2.3889    1  273.0   
505  0.04741   0.0  11.93     0  0.573  6.030  80.8  2.5050    1  273.0   

     PTRATIO       B  LSTAT  MEDV  
0       15.3  396.90   4.98  24.0  
1       17.8  396.90   9.14

In [20]:
#pandas DataFrame
boston_df=pd.DataFrame(boston_housing)

In [21]:
boston_df.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296.0   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242.0   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242.0   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222.0   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222.0   

   PTRATIO       B  LSTAT  MEDV  
0     15.3  396.90   4.98  24.0  
1     17.8  396.90   9.14  21.6  
2     17.8  392.83   4.03  34.7  
3     18.7  394.63   2.94  33.4  
4     18.7  396.90   5.33  36.2

In [22]:
boston_df.shape

(506, 14)

In [11]:
#importing the data from a csv file to a pandas DataFrame
diabetes_df=pd.read_csv('diabetes.csv')

In [12]:
type(diabetes_df)

pandas.core.frame.DataFrame

In [13]:
diabetes_df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [14]:
import pandas as pd
import numpy as np

# Define the number of rows and columns
num_rows = 100
num_columns = 5

# Generate random data
random_data = np.random.rand(num_rows, num_columns)

# Create a DataFrame from the random data
df = pd.DataFrame(random_data, columns=[f'Column_{i+1}' for i in range(num_columns)])

# Generate random labels
labels = np.random.choice(['A', 'B', 'C'], size=num_rows)

# Add the label column to the DataFrame
df['Label'] = labels

# Define the file path
file_path = 'random_dataset_with_labels.csv'

# Save the DataFrame to a CSV file
df.to_csv(file_path, index=False)

print(f'Dataset with labels saved to {file_path}')

Dataset with labels saved to random_dataset_with_labels.csv


In [3]:
x=np.ones((10,3) , dtype=int)

In [4]:
y=np.zeros((10,3) , dtype=int)

In [5]:
# Create a DataFrame from the random data
import numpy as np
z=np.concatenate((x,y),axis=0)

In [8]:
print(z)
import pandas as pd

[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


In [9]:
data=pd.DataFrame(z, columns=['A','B','C'])

In [11]:
print(data)
data.to_csv('data.csv',index=False)

    A  B  C
0   1  1  1
1   1  1  1
2   1  1  1
3   1  1  1
4   1  1  1
5   1  1  1
6   1  1  1
7   1  1  1
8   1  1  1
9   1  1  1
10  0  0  0
11  0  0  0
12  0  0  0
13  0  0  0
14  0  0  0
15  0  0  0
16  0  0  0
17  0  0  0
18  0  0  0
19  0  0  0


In [13]:
data.head(n=10)

A  B  C
0  1  1  1
1  1  1  1
2  1  1  1
3  1  1  1
4  1  1  1
5  1  1  1
6  1  1  1
7  1  1  1
8  1  1  1
9  1  1  1

In [25]:
# Step 1: Install the openpyxl library
!pip install openpyxl

# Step 2: Export the DataFrame to an Excel file



  Obtaining dependency information for openpyxl from https://files.pythonhosted.org/packages/58/d9/796181a30827b12101786c21301f0f4536597a9249530916b1fdb5bbad91/openpyxl-3.1.3-py2.py3-none-any.whl.metadata
  Obtaining dependency information for et-xmlfile from https://files.pythonhosted.org/packages/96/c2/3dd434b0108730014f1b96fd286040dc3bcb70066346f7e01ec2ac95865f/et_xmlfile-1.1.0-py3-none-any.whl.metadata
   ---------------------------------------- 0.0/251.3 kB ? eta -:--:--
   ---- ---------------------------------- 30.7/251.3 kB 660.6 kB/s eta 0:00:01
   ---- ---------------------------------- 30.7/251.3 kB 660.6 kB/s eta 0:00:01
   ---- ---------------------------------- 30.7/251.3 kB 660.6 kB/s eta 0:00:01
   ---- ---------------------------------- 30.7/251.3 kB 660.6 kB/s eta 0:00:01
   ----------------------- -------------- 153.6/251.3 kB 654.6 kB/s eta 0:00:01
   ----------------------- -------------- 153.6/251.3 kB 654.6 kB/s eta 0:00:01
   ----------------------------- ------


[notice] A new release of pip is available: 23.2.1 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip


In [23]:
boston_df.to_csv('boston.csv',index=False)

In [26]:
#export the pandas datafram to excel file 
boston_df.to_excel('boston.xlsx',index=False)

In [27]:
boston_df.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296.0   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242.0   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242.0   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222.0   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222.0   

   PTRATIO       B  LSTAT  MEDV  
0     15.3  396.90   4.98  24.0  
1     17.8  396.90   9.14  21.6  
2     17.8  392.83   4.03  34.7  
3     18.7  394.63   2.94  33.4  
4     18.7  396.90   5.33  36.2

In [28]:
#last 5 rows of the dataFrame
boston_df.tail()

CRIM   ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
501  0.06263  0.0  11.93     0  0.573  6.593  69.1  2.4786    1  273.0   
502  0.04527  0.0  11.93     0  0.573  6.120  76.7  2.2875    1  273.0   
503  0.06076  0.0  11.93     0  0.573  6.976  91.0  2.1675    1  273.0   
504  0.10959  0.0  11.93     0  0.573  6.794  89.3  2.3889    1  273.0   
505  0.04741  0.0  11.93     0  0.573  6.030  80.8  2.5050    1  273.0   

     PTRATIO       B  LSTAT  MEDV  
501     21.0  391.99   9.67  22.4  
502     21.0  396.90   9.08  20.6  
503     21.0  396.90   5.64  23.9  
504     21.0  393.45   6.48  22.0  
505     21.0  396.90   7.88  11.9

In [30]:
#information about DataFrame
boston_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 14 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   CRIM     506 non-null    float64
 1   ZN       506 non-null    float64
 2   INDUS    506 non-null    float64
 3   CHAS     506 non-null    int64  
 4   NOX      506 non-null    float64
 5   RM       506 non-null    float64
 6   AGE      506 non-null    float64
 7   DIS      506 non-null    float64
 8   RAD      506 non-null    int64  
 9   TAX      506 non-null    float64
 10  PTRATIO  506 non-null    float64
 11  B        506 non-null    float64
 12  LSTAT    506 non-null    float64
 13  MEDV     506 non-null    float64
dtypes: float64(12), int64(2)
memory usage: 55.5 KB


In [31]:
#finding the number of missing values in the DataFrame
boston_df.isnull().sum()

CRIM       0
ZN         0
INDUS      0
CHAS       0
NOX        0
RM         0
AGE        0
DIS        0
RAD        0
TAX        0
PTRATIO    0
B          0
LSTAT      0
MEDV       0
dtype: int64

In [33]:
diabetes= pd.read_csv('diabetes.csv')

In [34]:
diabetes.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [43]:
#counting the values based on labels 
diabetes.value_counts('Outcome')
diabetes.value_counts('Pregnancies')


Pregnancies
1     135
0     111
2     103
3      75
4      68
5      57
6      50
7      45
8      38
9      28
10     24
11     11
13     10
12      9
14      2
15      1
17      1
Name: count, dtype: int64

In [36]:
#group the values based on mean

In [49]:
diabetes.groupby('Outcome').mean()


Pregnancies     Glucose  BloodPressure  SkinThickness     Insulin  \
Outcome                                                                      
0           3.298000  109.980000      68.184000      19.664000   68.792000   
1           4.865672  141.257463      70.824627      22.164179  100.335821   

               BMI  DiabetesPedigreeFunction        Age  
Outcome                                                  
0        30.304200                  0.429734  31.190000  
1        35.142537                  0.550500  37.067164

In [50]:
diabetes.groupby('Outcome').std()

Pregnancies    Glucose  BloodPressure  SkinThickness     Insulin  \
Outcome                                                                     
0           3.017185  26.141200      18.063075      14.889947   98.865289   
1           3.741239  31.939622      21.491812      17.679711  138.689125   

              BMI  DiabetesPedigreeFunction        Age  
Outcome                                                 
0        7.689855                  0.299085  11.667655  
1        7.262967                  0.372354  10.968254

In [48]:
diabetes.groupby('Pregnancies').mean()

Glucose  BloodPressure  SkinThickness     Insulin        BMI  \
Pregnancies                                                                    
0            123.000000      67.153153      22.270270   81.675676  34.290090   
1            112.748148      67.792593      24.437037   98.674074  31.372593   
2            110.796117      63.252427      21.601942   85.844660  30.583495   
3            123.586667      66.586667      20.080000   87.453333  30.425333   
4            125.117647      70.029412      15.882353   69.441176  32.141176   
5            118.859649      76.210526      17.385965   57.298246  33.192982   
6            120.800000      68.420000      17.640000   63.580000  30.290000   
7            136.444444      70.777778      20.288889   84.466667  32.631111   
8            131.736842      75.184211      17.315789   92.815789  31.568421   
9            131.392857      77.892857      20.892857   62.428571  31.707143   
10           120.916667      70.208333      15.708333   34.791667  30.641667   
11           126.454545      74.181818      21.727273   65.454545  38.563636   
12           113.555556      76.333333      27.111111  112.555556  32.344444   
13           125.500000      73.800000      17.300000   27.900000  35.000000   
14           137.500000      70.000000      27.500000   92.000000  35.100000   
15           136.000000      70.000000      32.000000  110.000000  37.100000   
17           163.000000      72.000000      41.000000  114.000000  40.900000   

             DiabetesPedigreeFunction        Age   Outcome  
Pregnancies                                                 
0                            0.520838  27.603604  0.342342  
1                            0.486496  27.370370  0.214815  
2                            0.491660  27.194175  0.184466  
3                            0.432147  29.026667  0.360000  
4                            0.446353  32.779412  0.338235  
5                            0.396421  39.035088  0.368421  
6                            0.429520  39.340000  0.320000  
7                            0.443622  41.111111  0.555556  
8                            0.504711  45.368421  0.578947  
9                            0.550679  44.178571  0.642857  
10                           0.454167  42.666667  0.416667  
11                           0.522545  44.545455  0.636364  
12                           0.444333  47.444444  0.444444  
13                           0.463300  44.500000  0.500000  
14                           0.312000  42.000000  1.000000  
15                           0.153000  43.000000  1.000000  
17                           0.817000  47.000000  1.000000

In [44]:
#count or the number of values in the DataFrame
boston_df.count()

CRIM       506
ZN         506
INDUS      506
CHAS       506
NOX        506
RM         506
AGE        506
DIS        506
RAD        506
TAX        506
PTRATIO    506
B          506
LSTAT      506
MEDV       506
dtype: int64

In [45]:
#mean value column wise 

boston_df.mean()

CRIM         3.613524
ZN          11.363636
INDUS       11.136779
CHAS         0.069170
NOX          0.554695
RM           6.284634
AGE         68.574901
DIS          3.795043
RAD          9.549407
TAX        408.237154
PTRATIO     18.455534
B          356.674032
LSTAT       12.653063
MEDV        22.532806
dtype: float64

In [51]:
boston_df.min()

CRIM         0.00632
ZN           0.00000
INDUS        0.46000
CHAS         0.00000
NOX          0.38500
RM           3.56100
AGE          2.90000
DIS          1.12960
RAD          1.00000
TAX        187.00000
PTRATIO     12.60000
B            0.32000
LSTAT        1.73000
MEDV         5.00000
dtype: float64

In [52]:
#maximum value

In [53]:
boston_df.max()

CRIM        88.9762
ZN         100.0000
INDUS       27.7400
CHAS         1.0000
NOX          0.8710
RM           8.7800
AGE        100.0000
DIS         12.1265
RAD         24.0000
TAX        711.0000
PTRATIO     22.0000
B          396.9000
LSTAT       37.9700
MEDV        50.0000
dtype: float64

In [54]:
#all the statistical measures about the dataframe 
boston_df.describe()

CRIM          ZN       INDUS        CHAS         NOX          RM  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean     3.613524   11.363636   11.136779    0.069170    0.554695    6.284634   
std      8.601545   23.322453    6.860353    0.253994    0.115878    0.702617   
min      0.006320    0.000000    0.460000    0.000000    0.385000    3.561000   
25%      0.082045    0.000000    5.190000    0.000000    0.449000    5.885500   
50%      0.256510    0.000000    9.690000    0.000000    0.538000    6.208500   
75%      3.677083   12.500000   18.100000    0.000000    0.624000    6.623500   
max     88.976200  100.000000   27.740000    1.000000    0.871000    8.780000   

              AGE         DIS         RAD         TAX     PTRATIO           B  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean    68.574901    3.795043    9.549407  408.237154   18.455534  356.674032   
std     28.148861    2.105710    8.707259  168.537116    2.164946   91.294864   
min      2.900000    1.129600    1.000000  187.000000   12.600000    0.320000   
25%     45.025000    2.100175    4.000000  279.000000   17.400000  375.377500   
50%     77.500000    3.207450    5.000000  330.000000   19.050000  391.440000   
75%     94.075000    5.188425   24.000000  666.000000   20.200000  396.225000   
max    100.000000   12.126500   24.000000  711.000000   22.000000  396.900000   

            LSTAT        MEDV  
count  506.000000  506.000000  
mean    12.653063   22.532806  
std      7.141062    9.197104  
min      1.730000    5.000000  
25%      6.950000   17.025000  
50%     11.360000   21.200000  
75%     16.955000   25.000000  
max     37.970000   50.000000

In [60]:
#manipulating  a dataFrame
# adding a column to a dataFrame 
boston_df['price']=np.random.randint(100,1000);

In [61]:
boston_df.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296.0   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242.0   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242.0   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222.0   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222.0   

   PTRATIO       B  LSTAT  MEDV  price  
0     15.3  396.90   4.98  24.0    151  
1     17.8  396.90   9.14  21.6    151  
2     17.8  392.83   4.03  34.7    151  
3     18.7  394.63   2.94  33.4    151  
4     18.7  396.90   5.33  36.2    151

In [63]:
#removing a row
boston_df.drop(index=0,axis=0)

CRIM   ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
1    0.02731  0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242.0   
2    0.02729  0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242.0   
3    0.03237  0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222.0   
4    0.06905  0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222.0   
5    0.02985  0.0   2.18     0  0.458  6.430  58.7  6.0622    3  222.0   
..       ...  ...    ...   ...    ...    ...   ...     ...  ...    ...   
501  0.06263  0.0  11.93     0  0.573  6.593  69.1  2.4786    1  273.0   
502  0.04527  0.0  11.93     0  0.573  6.120  76.7  2.2875    1  273.0   
503  0.06076  0.0  11.93     0  0.573  6.976  91.0  2.1675    1  273.0   
504  0.10959  0.0  11.93     0  0.573  6.794  89.3  2.3889    1  273.0   
505  0.04741  0.0  11.93     0  0.573  6.030  80.8  2.5050    1  273.0   

     PTRATIO       B  LSTAT  MEDV  price  
1       17.8  396.90   9.14  21.6    151  
2       17.8  392.83   4.03  34.7    151  
3       18.7  394.63   2.94  33.4    151  
4       18.7  396.90   5.33  36.2    151  
5       18.7  394.12   5.21  28.7    151  
..       ...     ...    ...   ...    ...  
501     21.0  391.99   9.67  22.4    151  
502     21.0  396.90   9.08  20.6    151  
503     21.0  396.90   5.64  23.9    151  
504     21.0  393.45   6.48  22.0    151  
505     21.0  396.90   7.88  11.9    151  

[505 rows x 15 columns]

In [66]:
#removing a column
boston_df.drop(columns='ZN',axis=1)

CRIM  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  PTRATIO  \
0    0.00632   2.31     0  0.538  6.575  65.2  4.0900    1  296.0     15.3   
1    0.02731   7.07     0  0.469  6.421  78.9  4.9671    2  242.0     17.8   
2    0.02729   7.07     0  0.469  7.185  61.1  4.9671    2  242.0     17.8   
3    0.03237   2.18     0  0.458  6.998  45.8  6.0622    3  222.0     18.7   
4    0.06905   2.18     0  0.458  7.147  54.2  6.0622    3  222.0     18.7   
..       ...    ...   ...    ...    ...   ...     ...  ...    ...      ...   
501  0.06263  11.93     0  0.573  6.593  69.1  2.4786    1  273.0     21.0   
502  0.04527  11.93     0  0.573  6.120  76.7  2.2875    1  273.0     21.0   
503  0.06076  11.93     0  0.573  6.976  91.0  2.1675    1  273.0     21.0   
504  0.10959  11.93     0  0.573  6.794  89.3  2.3889    1  273.0     21.0   
505  0.04741  11.93     0  0.573  6.030  80.8  2.5050    1  273.0     21.0   

          B  LSTAT  MEDV  price  
0    396.90   4.98  24.0    151  
1    396.90   9.14  21.6    151  
2    392.83   4.03  34.7    151  
3    394.63   2.94  33.4    151  
4    396.90   5.33  36.2    151  
..      ...    ...   ...    ...  
501  391.99   9.67  22.4    151  
502  396.90   9.08  20.6    151  
503  396.90   5.64  23.9    151  
504  393.45   6.48  22.0    151  
505  396.90   7.88  11.9    151  

[506 rows x 14 columns]

In [67]:
#print a particular row 
boston_df.iloc[2]

CRIM         0.02729
ZN           0.00000
INDUS        7.07000
CHAS         0.00000
NOX          0.46900
RM           7.18500
AGE         61.10000
DIS          4.96710
RAD          2.00000
TAX        242.00000
PTRATIO     17.80000
B          392.83000
LSTAT        4.03000
MEDV        34.70000
price      151.00000
Name: 2, dtype: float64

In [69]:
#print a particular column
print(boston_df.iloc[:,0])#first column
print(boston_df.iloc[:,1])#second column
print(boston_df.iloc[:,-1])#last column

0      0.00632
1      0.02731
2      0.02729
3      0.03237
4      0.06905
        ...   
501    0.06263
502    0.04527
503    0.06076
504    0.10959
505    0.04741
Name: CRIM, Length: 506, dtype: float64
0      18.0
1       0.0
2       0.0
3       0.0
4       0.0
       ... 
501     0.0
502     0.0
503     0.0
504     0.0
505     0.0
Name: ZN, Length: 506, dtype: float64
0      151
1      151
2      151
3      151
4      151
      ... 
501    151
502    151
503    151
504    151
505    151
Name: price, Length: 506, dtype: int64


In [70]:
#positive correlation #negitive correlation
boston_df.corr()

CRIM        ZN     INDUS      CHAS       NOX        RM       AGE  \
CRIM     1.000000 -0.200469  0.406583 -0.055892  0.420972 -0.219247  0.352734   
ZN      -0.200469  1.000000 -0.533828 -0.042697 -0.516604  0.311991 -0.569537   
INDUS    0.406583 -0.533828  1.000000  0.062938  0.763651 -0.391676  0.644779   
CHAS    -0.055892 -0.042697  0.062938  1.000000  0.091203  0.091251  0.086518   
NOX      0.420972 -0.516604  0.763651  0.091203  1.000000 -0.302188  0.731470   
RM      -0.219247  0.311991 -0.391676  0.091251 -0.302188  1.000000 -0.240265   
AGE      0.352734 -0.569537  0.644779  0.086518  0.731470 -0.240265  1.000000   
DIS     -0.379670  0.664408 -0.708027 -0.099176 -0.769230  0.205246 -0.747881   
RAD      0.625505 -0.311948  0.595129 -0.007368  0.611441 -0.209847  0.456022   
TAX      0.582764 -0.314563  0.720760 -0.035587  0.668023 -0.292048  0.506456   
PTRATIO  0.289946 -0.391679  0.383248 -0.121515  0.188933 -0.355501  0.261515   
B       -0.385064  0.175520 -0.356977  0.048788 -0.380051  0.128069 -0.273534   
LSTAT    0.455621 -0.412995  0.603800 -0.053929  0.590879 -0.613808  0.602339   
MEDV    -0.388305  0.360445 -0.483725  0.175260 -0.427321  0.695360 -0.376955   
price         NaN       NaN       NaN       NaN       NaN       NaN       NaN   

              DIS       RAD       TAX   PTRATIO         B     LSTAT      MEDV  \
CRIM    -0.379670  0.625505  0.582764  0.289946 -0.385064  0.455621 -0.388305   
ZN       0.664408 -0.311948 -0.314563 -0.391679  0.175520 -0.412995  0.360445   
INDUS   -0.708027  0.595129  0.720760  0.383248 -0.356977  0.603800 -0.483725   
CHAS    -0.099176 -0.007368 -0.035587 -0.121515  0.048788 -0.053929  0.175260   
NOX     -0.769230  0.611441  0.668023  0.188933 -0.380051  0.590879 -0.427321   
RM       0.205246 -0.209847 -0.292048 -0.355501  0.128069 -0.613808  0.695360   
AGE     -0.747881  0.456022  0.506456  0.261515 -0.273534  0.602339 -0.376955   
DIS      1.000000 -0.494588 -0.534432 -0.232471  0.291512 -0.496996  0.249929   
RAD     -0.494588  1.000000  0.910228  0.464741 -0.444413  0.488676 -0.381626   
TAX     -0.534432  0.910228  1.000000  0.460853 -0.441808  0.543993 -0.468536   
PTRATIO -0.232471  0.464741  0.460853  1.000000 -0.177383  0.374044 -0.507787   
B        0.291512 -0.444413 -0.441808 -0.177383  1.000000 -0.366087  0.333461   
LSTAT   -0.496996  0.488676  0.543993  0.374044 -0.366087  1.000000 -0.737663   
MEDV     0.249929 -0.381626 -0.468536 -0.507787  0.333461 -0.737663  1.000000   
price         NaN       NaN       NaN       NaN       NaN       NaN       NaN   

         price  
CRIM       NaN  
ZN         NaN  
INDUS      NaN  
CHAS       NaN  
NOX        NaN  
RM         NaN  
AGE        NaN  
DIS        NaN  
RAD        NaN  
TAX        NaN  
PTRATIO    NaN  
B          NaN  
LSTAT      NaN  
MEDV       NaN  
price      NaN

In [71]:
#Matplotlib --> useful for making pots


In [72]:
import matplotlib.pyplot as plt
import numpy as np

In [73]:
x=np.linspace(0,10,100)

In [74]:
print(x)

[ 0.          0.1010101   0.2020202   0.3030303   0.4040404   0.50505051
  0.60606061  0.70707071  0.80808081  0.90909091  1.01010101  1.11111111
  1.21212121  1.31313131  1.41414141  1.51515152  1.61616162  1.71717172
  1.81818182  1.91919192  2.02020202  2.12121212  2.22222222  2.32323232
  2.42424242  2.52525253  2.62626263  2.72727273  2.82828283  2.92929293
  3.03030303  3.13131313  3.23232323  3.33333333  3.43434343  3.53535354
  3.63636364  3.73737374  3.83838384  3.93939394  4.04040404  4.14141414
  4.24242424  4.34343434  4.44444444  4.54545455  4.64646465  4.74747475
  4.84848485  4.94949495  5.05050505  5.15151515  5.25252525  5.35353535
  5.45454545  5.55555556  5.65656566  5.75757576  5.85858586  5.95959596
  6.06060606  6.16161616  6.26262626  6.36363636  6.46464646  6.56565657
  6.66666667  6.76767677  6.86868687  6.96969697  7.07070707  7.17171717
  7.27272727  7.37373737  7.47474747  7.57575758  7.67676768  7.77777778
  7.87878788  7.97979798  8.08080808  8.18181818  8